"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, FileText, Save, Send } from "lucide-react";
import { createClient } from "../../../lib/supabase/browser";

type Deal = { id:string; deal_code:string; client_name:string; organization:string; project_name:string; project_type:string; project_description:string|null; technology:string|null; start_date:string|null; expected_delivery_date:string|null; total_amount:number; advance_amount:number; remaining_amount:number; payment_schedule:string|null; revision_rounds:number; support_days:number };

export default function NewAgreementPage(){
 const [code,setCode]=useState(""); const [deal,setDeal]=useState<Deal|null>(null); const [loading,setLoading]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [saved,setSaved]=useState(false);
 const [notes,setNotes]=useState("This agreement covers the development scope, commercial terms, delivery expectations and support described below.");
 async function load(e?:FormEvent, overrideCode?:string){e?.preventDefault();const lookup=(overrideCode??code).trim().toUpperCase();if(!lookup)return;setLoading(true);setError("");setDeal(null);const s=createClient();const {data,error}=await s.from("deals").select("*").eq("deal_code",lookup).single();if(error||!data)setError(error?.message||"Deal not found.");else setDeal(data as Deal);setLoading(false);}
 useEffect(()=>{const query=new URLSearchParams(window.location.search);const dealCode=query.get("deal");if(dealCode){const normalized=dealCode.toUpperCase();setCode(normalized);void load(undefined,normalized);}},[]);
 async function save(send=false){if(!deal)return;setSaving(true);setError("");const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user){window.location.href="/login";return;}const snapshot={deal,notes,generatedAt:new Date().toISOString()};const {data:a,error}=await s.from("agreements").insert({deal_id:deal.id,status:send?"sent":"draft",sent_at:send?new Date().toISOString():null}).select("id,agreement_code").single();if(error||!a){setError(error?.message||"Unable to create agreement.");setSaving(false);return;}const {error:v}=await s.from("agreement_versions").insert({agreement_id:a.id,version:1,snapshot});if(v){setError(v.message);setSaving(false);return;}setSaved(true);setSaving(false);if(send)window.location.href=`/agreements/${a.id}`;}
 const delivery=useMemo(()=>deal?.expected_delivery_date?new Date(deal.expected_delivery_date).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}):"To be agreed",[deal]);
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">R</div><div><div className="brand-title">Rahul Development Studio</div><div className="brand-subtitle">Client Management</div></div></div><nav className="nav"><a className="nav-item" href="/">Dashboard</a><a className="nav-item active" href="/agreements">Agreements</a><a className="nav-item" href="/projects">Projects</a><a className="nav-item" href="/clients">Clients</a><a className="nav-item" href="/completed">Completed</a><a className="nav-item" href="/settings">Settings</a></nav></aside>
 <main className="main agreement-main"><div className="form-topbar"><div><a className="back-link" href="/agreements"><ArrowLeft size={15}/> Back to agreements</a><div className="eyebrow">Agreement editor</div><h1>Create Project Development Agreement</h1><p className="page-copy">Start from a saved deal. Signed versions are immutable.</p></div></div>
 <section className="lookup-card"><div><div className="panel-title">Load a deal</div><p className="page-copy">Enter the Deal ID generated when you saved the deal. If you arrived from Create Deal, it is loaded automatically.</p></div><form onSubmit={load} className="lookup-form"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="RDS-XXXXXXXX" required/><button className="btn primary" disabled={loading}>{loading?"Loading…":"Load Deal"}</button></form></section>
 {error&&<div className="form-error deal-error">{error}</div>}
 {deal&&<div className="agreement-layout"><section className="agreement-paper"><div className="agreement-header"><div><div className="agreement-brand">RAHUL DEVELOPMENT STUDIO</div><h2>PROJECT DEVELOPMENT AGREEMENT</h2></div><div className="agreement-badge">DRAFT · v1</div></div>
 <div className="agreement-meta"><Meta label="Deal ID" value={deal.deal_code}/><Meta label="Client" value={deal.client_name}/><Meta label="Project" value={deal.project_name}/><Meta label="Organization" value={deal.organization}/></div>
 <Section title="1. Parties"><p>This Project Development Agreement is entered into between <strong>Rahul Development Studio</strong> and <strong>{deal.client_name}</strong>{deal.organization?` (${deal.organization})`:""} for the development of <strong>{deal.project_name}</strong>.</p></Section>
 <Section title="2. Project Scope"><p>{deal.project_description||"The project will be developed according to the scope and deliverables agreed by the parties."}</p><p>Project type: <strong>{deal.project_type}</strong>. Technology: <strong>{deal.technology||"As mutually agreed"}</strong>.</p></Section>
 <Section title="3. Commercial Terms"><Info items={[["Total project amount",money(deal.total_amount)],["Advance",money(deal.advance_amount)],["Remaining",money(deal.remaining_amount)],["Payment schedule",deal.payment_schedule||"As mutually agreed"]]}/></Section>
 <Section title="4. Timeline & Support"><Info items={[["Start date",deal.start_date||"To be agreed"],["Expected delivery",delivery],["Revision rounds",String(deal.revision_rounds)],["Bug-fix support",`${deal.support_days} days`]]}/></Section>
 <Section title="5. Scope & Deliverables"><p>Scope and deliverables are inherited from the saved deal and will form part of this agreement.</p></Section>
 <Section title="6. Agreement Notes"><textarea className="agreement-notes" value={notes} onChange={e=>setNotes(e.target.value)} rows={4}/></Section>
 <div className="declaration"><strong>Client Declaration</strong><p>The client confirms that they have reviewed this agreement and will sign the final version electronically.</p></div><div className="signature-placeholder"><div>CLIENT SIGNATURE<span>Pending client review</span></div><div>DEVELOPER COUNTERSIGN<span>Pending execution</span></div></div>
 </section><aside className="agreement-actions panel"><div className="panel-title"><FileText size={16}/> Agreement actions</div><p className="page-copy">Save a private draft first. Send to Client moves it into review.</p><button className="btn" onClick={()=>save(false)} disabled={saving}><Save size={15}/> {saved?"Draft Saved":"Save Agreement"}</button><button className="btn primary" onClick={()=>save(true)} disabled={saving}><Send size={15}/> {saving?"Saving…":"Send to Client"}</button><p className="action-note">Once signed, this version is locked. Later changes must use a new amendment/version.</p></aside></div>}
 </main></div>;
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="agreement-section"><h3>{title}</h3>{children}</section>}
function Meta({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function Info({items}:{items:string[][]}){return <div className="agreement-info-grid">{items.map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div>}
function money(v:number){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v||0)}
