"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, Clock3, LogOut, MessageSquare, ShieldCheck } from "lucide-react";
import { createClient } from "../../lib/supabase/browser";

type Project = { id: string; project_code: string; project_name: string; status: string; start_date: string | null; expected_date: string | null };
type Phase = { id: string; name: string; phase_order: number };
type Topic = { id: string; phase_id: string; title: string; status: string };
type Agreement = { id: string; agreement_code: string; status: string; deal_id: string };
type Deal = { project_name: string; expected_delivery_date: string | null };

export default function ClientPortal() {
  const [project,setProject]=useState<Project|null>(null),[phases,setPhases]=useState<Phase[]>([]),[topics,setTopics]=useState<Topic[]>([]),[agreement,setAgreement]=useState<Agreement|null>(null),[deal,setDeal]=useState<Deal|null>(null),[name,setName]=useState("Client"),[loading,setLoading]=useState(true),[error,setError]=useState("");
  useEffect(()=>{(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){window.location.href="/login";return;}const {data:p}=await s.from("profiles").select("full_name").eq("id",user.id).single();setName(p?.full_name||"Client");const {data:pr,error:e}=await s.from("projects").select("*").eq("client_id",user.id).order("created_at",{ascending:false}).limit(1).single();if(e||!pr){setError("Your project portal is not active yet.");setLoading(false);return;}setProject(pr);const [{data:ag},{data:ph},{data:to}]=await Promise.all([s.from("agreements").select("id,agreement_code,status,deal_id").eq("project_id",pr.id).single(),s.from("project_phases").select("id,name,phase_order").eq("project_id",pr.id).order("phase_order"),s.from("phase_topics").select("id,phase_id,title,status").eq("project_id",pr.id).order("created_at")]);setAgreement(ag);setPhases(ph||[]);setTopics(to||[]);if(ag){const {data:d}=await s.from("deals").select("project_name,expected_delivery_date").eq("id",ag.deal_id).single();setDeal(d);}setLoading(false);})()},[]);
  const completed=useMemo(()=>topics.filter(t=>t.status==="completed").length,[topics]); const progress=topics.length?Math.round(completed/topics.length*100):0;
  async function logout(){await createClient().auth.signOut();window.location.href="/login";}
  if(loading)return <div className="auth-shell"><div className="panel">Loading your portal…</div></div>;
  if(error)return <div className="auth-shell"><div className="panel"><div className="form-error">{error}</div></div></div>;
  return <main className="client-shell"><header className="client-header"><div className="brand"><div className="brand-mark">R</div><div><div className="brand-title">Rahul Development Studio</div><div className="brand-subtitle">Client Portal</div></div></div><button className="btn" onClick={logout}><LogOut size={15}/> Sign out</button></header><div className="client-main"><div className="eyebrow">CLIENT PORTAL</div><h1>Welcome, {name}</h1><p className="page-copy">A private view of your agreement, project progress and delivery timeline.</p><div className="client-hero panel"><div><div className="eyebrow">PROJECT</div><h2>{project?.project_name||deal?.project_name}</h2><span className="status">{project?.status?.replaceAll("_"," ")}</span></div><div className="hero-progress"><strong>{progress}%</strong><span>Project progress</span><div className="progress"><span style={{width:`${progress}%`}}/></div></div></div><div className="client-grid"><section className="panel"><div className="panel-header"><div className="panel-title">Project timeline</div><span className="status"><Clock3 size={12}/> {project?.expected_date||deal?.expected_delivery_date||"TBD"}</span></div><div className="timeline">{phases.map((phase,i)=>{const ts=topics.filter(t=>t.phase_id===phase.id);const done=ts.length>0&&ts.every(t=>t.status==="completed");return <div className="timeline-item" key={phase.id}><div className={`timeline-icon ${done?"done":""}`}>{done?<Check size={13}/>:i+1}</div><div><strong>{phase.name}</strong><p>{ts.length?`${ts.filter(t=>t.status==="completed").length}/${ts.length} topics completed`:"Phase not started"}</p></div></div>})}{!phases.length&&<p className="page-copy">Your development phases will appear here once the developer starts the project.</p>}</div></section><aside className="panel"><div className="panel-title"><ShieldCheck size={16}/> Agreement</div><p className="page-copy">{agreement?.agreement_code}</p><div className="portal-card-row"><span>Status</span><strong>{agreement?.status?.replaceAll("_"," ")}</strong></div><a className="btn" href={agreement?`/agreements/${agreement.id}`:"#"}>View agreement</a><div className="action-divider"/><div className="panel-title"><MessageSquare size={16}/> Need a change?</div><p className="page-copy">Corrections to the signed agreement must be handled through an amendment.</p></aside></div></div></main>;
}
