"use client";

import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, Check, Copy, MessageSquare, PenLine, Send, ShieldCheck } from "lucide-react";
import { createClient } from "../../../lib/supabase/browser";

type Agreement = { id:string; agreement_code:string; deal_id:string; client_id:string|null; status:string; version:number; created_at:string };
type Deal = { deal_code:string; client_name:string; organization:string; project_name:string; project_type:string; project_description:string|null; technology:string|null; start_date:string|null; expected_delivery_date:string|null; total_amount:number; advance_amount:number; remaining_amount:number; payment_schedule:string|null; revision_rounds:number; support_days:number };
type Version = { version:number; snapshot:{ deal:Deal; notes:string }; created_at:string };
type Item = { title:string; item_order:number };
type Profile = { id:string; role:string; full_name:string|null };

export default function AgreementDetailPage({ params }:{ params:{ id:string } }) {
 const [agreement,setAgreement]=useState<Agreement|null>(null),[deal,setDeal]=useState<Deal|null>(null),[version,setVersion]=useState<Version|null>(null),[scope,setScope]=useState<Item[]>([]),[deliverables,setDeliverables]=useState<Item[]>([]),[profile,setProfile]=useState<Profile|null>(null);
 const [correction,setCorrection]=useState(false),[signing,setSigning]=useState(false),[section,setSection]=useState("General"),[request,setRequest]=useState(""),[signerName,setSignerName]=useState(""),[signature,setSignature]=useState(""),[accepted,setAccepted]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false);
 useEffect(()=>{(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){window.location.href="/login";return;}const {data:p}=await s.from("profiles").select("id,role,full_name").eq("id",user.id).single();setProfile(p);const {data:a,error:ae}=await s.from("agreements").select("*").eq("id",params.id).single();if(ae||!a){setError(ae?.message||"Agreement not found.");setLoading(false);return;}setAgreement(a);const [{data:d},{data:v},{data:sc},{data:de}]=await Promise.all([s.from("deals").select("*").eq("id",a.deal_id).single(),s.from("agreement_versions").select("version,snapshot,created_at").eq("agreement_id",a.id).order("version",{ascending:false}).limit(1).single(),s.from("deal_scope").select("title,item_order").eq("deal_id",a.deal_id).order("item_order"),s.from("deal_deliverables").select("title,item_order").eq("deal_id",a.deal_id).order("item_order")]);setDeal(d);setVersion(v);setScope(sc||[]);setDeliverables(de||[]);if(p?.full_name)setSignerName(p.full_name);setLoading(false);})()},[params.id]);
 async function submitCorrection(e:FormEvent){e.preventDefault();if(!request.trim()||!agreement)return;setSubmitting(true);setError("");const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){setError("Please sign in again.");setSubmitting(false);return;}const {error:e1}=await s.from("correction_requests").insert({agreement_id:agreement.id,client_id:user.id,section,request_text:request.trim()});if(e1)setError(e1.message);else{setMessage("Correction request submitted.");setRequest("");setCorrection(false);}setSubmitting(false);}
 async function signAgreement(){if(!agreement||!accepted||!signerName.trim()||!signature.trim())return;setSubmitting(true);setError("");const s=createClient();const {error:e}=await s.rpc("client_sign_agreement",{p_agreement_id:agreement.id,p_signer_name:signerName.trim(),p_signature_data:signature.trim()});if(e)setError(e.message);else{setAgreement({...agreement,status:"client_signed"});setMessage("Agreement signed successfully. It is now waiting for developer countersignature.");setSigning(false);}setSubmitting(false);}
 async function countersign(){if(!agreement||!signerName.trim()||!signature.trim())return;setSubmitting(true);setError("");const s=createClient();const {data,error:e}=await s.rpc("developer_countersign_agreement",{p_agreement_id:agreement.id,p_signer_name:signerName.trim(),p_signature_data:signature.trim()});if(e)setError(e.message);else{setAgreement({...agreement,status:"executed"});setMessage(`Agreement executed. Project ${data?.project_id?"is now active":"created"}.`);setSigning(false);}setSubmitting(false);}
 async function copyLink(){await navigator.clipboard.writeText(window.location.href);setMessage("Private agreement link copied.");}
 if(loading)return <div className="auth-shell"><div className="panel">Loading agreement…</div></div>;
 if(error&&!agreement)return <div className="auth-shell"><div className="panel"><div className="form-error">{error}</div><a className="btn" href="/agreements">Back to agreements</a></div></div>;
 if(!agreement||!deal)return null;
 const status=agreement.status.replaceAll("_"," ");const isClient=profile?.role==="client";const isDeveloper=profile?.role==="developer";
 const canClientSign=isClient&&agreement.client_id===profile?.id&&["sent","under_review"].includes(agreement.status);const canCountersign=isDeveloper&&agreement.status==="client_signed";
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">R</div><div><div className="brand-title">Rahul Development Studio</div><div className="brand-subtitle">Client Management</div></div></div><nav className="nav"><a className="nav-item" href="/">Dashboard</a><a className="nav-item active" href="/agreements">Agreements</a><a className="nav-item" href="/projects">Projects</a><a className="nav-item" href="/clients">Clients</a><a className="nav-item" href="/completed">Completed</a><a className="nav-item" href="/settings">Settings</a></nav></aside>
 <main className="main agreement-main"><a className="back-link" href="/agreements"><ArrowLeft size={15}/> Back to agreements</a><div className="detail-topbar"><div><div className="eyebrow">Agreement {agreement.agreement_code}</div><h1>{deal.project_name}</h1><p className="page-copy">{deal.client_name}{deal.organization?` · ${deal.organization}`:""}</p></div><div className="detail-actions"><span className={`status status-${agreement.status}`}>{status}</span><button className="btn" onClick={copyLink}><Copy size={15}/> Copy private link</button></div></div>
 {message&&<div className="success-banner"><Check size={15}/>{message}</div>}{error&&agreement&&<div className="form-error deal-error">{error}</div>}
 <div className="agreement-layout"><section className="agreement-paper"><div className="agreement-header"><div><div className="agreement-brand">RAHUL DEVELOPMENT STUDIO</div><h2>PROJECT DEVELOPMENT AGREEMENT</h2></div><div className="agreement-badge">{agreement.status.toUpperCase()} · v{agreement.version}</div></div><div className="agreement-meta"><Meta label="Agreement ID" value={agreement.agreement_code}/><Meta label="Deal ID" value={deal.deal_code}/><Meta label="Client" value={deal.client_name}/><Meta label="Project" value={deal.project_name}/></div>
 <Section title="1. Parties"><p>This Project Development Agreement is entered into between <strong>Rahul Development Studio</strong> and <strong>{deal.client_name}</strong>{deal.organization?` (${deal.organization})`:""} for <strong>{deal.project_name}</strong>.</p></Section><Section title="2. Project Scope"><p>{deal.project_description||"The project will be developed according to the agreed scope and deliverables."}</p><p>Project type: <strong>{deal.project_type}</strong>. Technology: <strong>{deal.technology||"As mutually agreed"}</strong>.</p></Section><Section title="3. Commercial Terms"><Info items={[["Total project amount",money(deal.total_amount)],["Advance",money(deal.advance_amount)],["Remaining",money(deal.remaining_amount)],["Payment schedule",deal.payment_schedule||"As mutually agreed"]]}/></Section><Section title="4. Timeline & Support"><Info items={[["Start date",deal.start_date||"To be agreed"],["Expected delivery",deal.expected_delivery_date||"To be agreed"],["Revision rounds",String(deal.revision_rounds)],["Bug-fix support",`${deal.support_days} days`]]}/></Section><Section title="5. Scope & Deliverables"><div className="two-list"><div><strong>Scope</strong>{scope.length?scope.map(x=><p key={x.title}>• {x.title}</p>):<p>As agreed in project brief.</p>}</div><div><strong>Deliverables</strong>{deliverables.length?deliverables.map(x=><p key={x.title}>• {x.title}</p>):<p>As agreed in project brief.</p>}</div></div></Section><Section title="6. Agreement Notes"><p>{version?.snapshot?.notes||"No additional notes."}</p></Section><div className="declaration"><strong>Client Declaration</strong><p>I have reviewed the agreement and understand that any correction must be requested before signing. Once signed, this version becomes immutable.</p></div><div className="signature-placeholder"><div>CLIENT SIGNATURE<span>{agreement.status==="client_signed"||agreement.status==="executed"?"Signed":"Pending client signature"}</span></div><div>DEVELOPER COUNTERSIGN<span>{agreement.status==="executed"?"Executed":"Pending developer countersign"}</span></div></div></section>
 <aside className="agreement-actions panel"><div className="panel-title"><ShieldCheck size={16}/> Review & actions</div><p className="page-copy">This page shows the exact agreement version currently stored for this deal.</p>{canClientSign&&<button className="btn primary" onClick={()=>setSigning(true)}><PenLine size={15}/> Sign Agreement</button>}{canCountersign&&<button className="btn primary" onClick={()=>setSigning(true)}><PenLine size={15}/> Countersign & Activate Project</button>}{agreement.status==="executed"&&<div className="success-banner compact"><Check size={15}/> Agreement executed</div>}{isClient&&canClientSign&&<button className="btn" onClick={()=>setCorrection(true)}><MessageSquare size={15}/> Request correction</button>}<div className="action-divider"/><div className="action-note"><strong>Version {agreement.version}</strong><br/>Created {new Date(agreement.created_at).toLocaleString("en-IN")}.<br/><br/>Signed versions are immutable. Future changes must use an amendment.</div></aside></div>
 {signing&&<div className="modal-backdrop"><div className="modal panel"><div className="panel-title"><PenLine size={16}/> {canCountersign?"Developer countersign":"Confirm & sign agreement"}</div><p className="page-copy">Your signature will be recorded with this agreement version and timestamped.</p><label>Full name<input value={signerName} onChange={e=>setSignerName(e.target.value)} placeholder="Full legal name" required/></label><label>Signature<textarea value={signature} onChange={e=>setSignature(e.target.value)} rows={3} placeholder="Type your full name as your electronic signature" required/></label>{canClientSign&&<label className="check-row"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/> I have reviewed the agreement and agree to its terms.</label>}<div className="modal-actions"><button className="btn" onClick={()=>setSigning(false)}>Cancel</button><button className="btn primary" disabled={submitting||!signerName.trim()||!signature.trim()||(canClientSign&&!accepted)} onClick={canCountersign?countersign:signAgreement}>{submitting?"Signing…":canCountersign?"Countersign & Activate":"Confirm & Sign Agreement"}</button></div></div></div>}
 {correction&&<div className="modal-backdrop"><form className="modal panel" onSubmit={submitCorrection}><div className="panel-title">Request a correction</div><p className="page-copy">Tell the developer exactly what needs to change. You cannot edit agreement data directly.</p><label>Section<select value={section} onChange={e=>setSection(e.target.value)}><option>General</option><option>Project Scope</option><option>Commercial Terms</option><option>Timeline & Support</option><option>Scope & Deliverables</option><option>Other</option></select></label><label>What needs correction?<textarea value={request} onChange={e=>setRequest(e.target.value)} rows={5} placeholder="Example: The project amount should be ₹18,000." required/></label><div className="modal-actions"><button type="button" className="btn" onClick={()=>setCorrection(false)}>Cancel</button><button className="btn primary" disabled={submitting}><Send size={15}/>{submitting?"Submitting…":"Submit request"}</button></div></form></div>}
 </main></div>;
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="agreement-section"><h3>{title}</h3>{children}</section>}function Meta({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}function Info({items}:{items:string[][]}){return <div className="agreement-info-grid">{items.map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div>}function money(v:number){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v||0)}
