"use client";

import { FormEvent, useEffect, useState, type ReactNode } from "react";
import { ArrowLeft, Check, Copy, Download, KeyRound, MessageSquare, PenLine, Send, ShieldCheck } from "lucide-react";
import { createClient } from "../../../lib/supabase/browser";

type Agreement={id:string;agreement_code:string;deal_id:string;client_id:string|null;status:string;version:number;created_at:string};
type Deal={deal_code:string;client_name:string;organization:string;project_name:string;project_type:string;project_description:string|null;technology:string|null;start_date:string|null;expected_delivery_date:string|null;total_amount:number;advance_amount:number;remaining_amount:number;payment_schedule:string|null;revision_rounds:number;support_days:number};
type Version={version:number;snapshot:{deal:Deal;notes?:string};created_at:string};
type Item={title:string;item_order:number};
type Profile={id:string;role:string;full_name:string|null};
type Credentials={clientId:string;email:string;temporaryPassword:string;mustChangePassword:boolean};
type Document={storage_path:string;content_hash:string|null;version:number;generated_at:string};

async function createPrivateToken(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);const token=Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("");const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token));const hash=Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,"0")).join("");return {token,hash};}

export default function AgreementDetailPage({params}:{params:Promise<{id:string}>}){
 const [agreementId,setAgreementId]=useState("");
 const [agreement,setAgreement]=useState<Agreement|null>(null),[deal,setDeal]=useState<Deal|null>(null),[version,setVersion]=useState<Version|null>(null),[scope,setScope]=useState<Item[]>([]),[deliverables,setDeliverables]=useState<Item[]>([]),[profile,setProfile]=useState<Profile|null>(null),[document,setDocument]=useState<Document|null>(null);
 const [correction,setCorrection]=useState(false),[signing,setSigning]=useState(false),[section,setSection]=useState("General"),[request,setRequest]=useState(""),[signerName,setSignerName]=useState(""),[signature,setSignature]=useState(""),[accepted,setAccepted]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false),[linkBusy,setLinkBusy]=useState(false),[credentials,setCredentials]=useState<Credentials|null>(null),[provisioning,setProvisioning]=useState(false),[pdfBusy,setPdfBusy]=useState(false);
 useEffect(()=>{let active=true;(async()=>{const resolved=await params;if(active)setAgreementId(resolved.id)})();return()=>{active=false}},[params]);
 useEffect(()=>{if(!agreementId)return;(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){window.location.href="/login";return;}const {data:p}=await s.from("profiles").select("id,role,full_name").eq("id",user.id).single();setProfile(p);const {data:a,error:ae}=await s.from("agreements").select("*").eq("id",agreementId).single();if(ae||!a){setError(ae?.message||"Agreement not found.");setLoading(false);return;}setAgreement(a);const [{data:d},{data:v},{data:sc},{data:de},{data:doc}]=await Promise.all([s.from("deals").select("*").eq("id",a.deal_id).single(),s.from("agreement_versions").select("version,snapshot,created_at").eq("agreement_id",a.id).order("version",{ascending:false}).limit(1).single(),s.from("deal_scope").select("title,item_order").eq("deal_id",a.deal_id).order("item_order"),s.from("deal_deliverables").select("title,item_order").eq("deal_id",a.deal_id).order("item_order"),s.from("agreement_documents").select("storage_path,content_hash,version,generated_at").eq("agreement_id",a.id).order("version",{ascending:false}).limit(1).maybeSingle()]);setDeal(d);setVersion(v);setScope(sc||[]);setDeliverables(de||[]);setDocument(doc);if(p?.full_name)setSignerName(p.full_name);setLoading(false);})()},[agreementId]);
 async function sendPrivateLink(){if(!agreement)return;setLinkBusy(true);setError("");try{const {token,hash}=await createPrivateToken();const s=createClient();const {error:e}=await s.rpc("issue_agreement_access_token",{p_agreement_id:agreement.id,p_token_hash:hash});if(e)throw e;const url=`${window.location.origin}/agreement/${token}`;await navigator.clipboard.writeText(url);setAgreement({...agreement,status:agreement.status==="draft"?"sent":agreement.status});setMessage("Private client review link generated and copied.");}catch(e){setError(e instanceof Error?e.message:"Unable to create private link.")}finally{setLinkBusy(false)}}
 async function submitCorrection(e:FormEvent){e.preventDefault();if(!request.trim()||!agreement)return;setSubmitting(true);setError("");const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){setError("Please sign in again.");setSubmitting(false);return;}const {error:e1}=await s.from("correction_requests").insert({agreement_id:agreement.id,client_id:user.id,section,request_text:request.trim()});if(e1)setError(e1.message);else{setMessage("Correction request submitted.");setRequest("");setCorrection(false);}setSubmitting(false)}
 async function provisionPortal(){if(!agreement)return;setProvisioning(true);setError("");try{const response=await fetch("/api/clients/provision",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({agreementId:agreement.id})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to provision client portal.");setCredentials(data);setMessage("Client portal access has been provisioned.");}catch(e){setError(e instanceof Error?e.message:"Unable to provision client portal.")}finally{setProvisioning(false)}}
 async function generateSignedPdf(){if(!agreement)return;setPdfBusy(true);setError("");try{const s=createClient();const {data,error:e}=await s.functions.invoke("generate-signed-agreement-pdf",{body:{agreementId:agreement.id}});if(e)throw e;if(data?.error)throw new Error(data.error);const {data:doc}=await s.from("agreement_documents").select("storage_path,content_hash,version,generated_at").eq("agreement_id",agreement.id).order("version",{ascending:false}).limit(1).single();setDocument(doc);setMessage("Final signed PDF generated and securely stored in Supabase Storage.");}catch(e){setError(e instanceof Error?e.message:"Unable to generate signed PDF.")}finally{setPdfBusy(false)}}
 async function openSignedPdf(){if(!document)return;const s=createClient();const {data,error:e}=await s.storage.from("signed-agreements").createSignedUrl(document.storage_path,3600);if(e||!data?.signedUrl){setError(e?.message||"Unable to create secure PDF link.");return;}window.open(data.signedUrl,"_blank","noopener,noreferrer")}
 async function signAgreement(){if(!agreement||!accepted||!signerName.trim()||!signature.trim())return;setSubmitting(true);setError("");const s=createClient();const {error:e}=await s.rpc("client_sign_agreement",{p_agreement_id:agreement.id,p_signer_name:signerName.trim(),p_signature_data:signature.trim()});if(e)setError(e.message);else{setAgreement({...agreement,status:"client_signed"});setMessage("Agreement signed successfully. It is now waiting for developer countersignature.");setSigning(false);}setSubmitting(false)}
 async function countersign(){if(!agreement||!signerName.trim()||!signature.trim())return;setSubmitting(true);setError("");const s=createClient();const {error:e}=await s.rpc("developer_countersign_agreement",{p_agreement_id:agreement.id,p_signer_name:signerName.trim(),p_signature_data:signature.trim()});if(e){setError(e.message);setSubmitting(false);return;}setAgreement({...agreement,status:"executed"});setSigning(false);setMessage("Agreement executed. Generating final signed PDF and activating the client portal…");await provisionPortal();await generateSignedPdf();setSubmitting(false)}
 async function copyLink(){await navigator.clipboard.writeText(window.location.href);setMessage("Link copied to clipboard.")}
 async function copy(value:string){await navigator.clipboard.writeText(value);setMessage("Copied to clipboard.")}
 if(loading)return <div className="auth-shell"><div className="panel">Loading agreement…</div></div>;
 if(error&&!agreement)return <div className="auth-shell"><div className="panel"><div className="form-error">{error}</div><a className="btn" href="/agreements">Back to agreements</a></div></div>;
 if(!agreement||!deal)return null;
 const isClient=profile?.role==="client",isDeveloper=profile?.role==="developer",status=agreement.status.replaceAll("_"," ");
 const canClientSign=isClient&&agreement.client_id===profile?.id&&["sent","under_review"].includes(agreement.status),canCountersign=isDeveloper&&agreement.status==="client_signed";
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">R</div><div><div className="brand-title">Rahul Development Studio</div><div className="brand-subtitle">Client Management</div></div></div><nav className="nav"><a className="nav-item" href="/">Dashboard</a><a className="nav-item active" href="/agreements">Agreements</a><a className="nav-item" href="/projects">Projects</a><a className="nav-item" href="/clients">Clients</a><a className="nav-item" href="/completed">Completed</a><a className="nav-item" href="/settings">Settings</a></nav></aside><main className="main agreement-main"><a className="back-link" href="/agreements"><ArrowLeft size={15}/> Back to agreements</a><div className="detail-topbar"><div><div className="eyebrow">Agreement {agreement.agreement_code}</div><h1>{deal.project_name}</h1><p className="page-copy">{deal.client_name}{deal.organization?` · ${deal.organization}`:""}</p></div><div className="detail-actions"><span className={`status status-${agreement.status}`}>{status}</span>{isDeveloper&&agreement.status!=="executed"&&<button className="btn primary" disabled={linkBusy} onClick={sendPrivateLink}><Send size={15}/>{linkBusy?"Generating…":"Send private link"}</button>}<button className="btn" onClick={copyLink}><Copy size={15}/> Copy link</button></div></div>{message&&<div className="success-banner"><Check size={15}/>{message}</div>}{error&&agreement&&<div className="form-error deal-error">{error}</div>}
 <div className="agreement-layout"><section className="agreement-paper"><div className="agreement-header"><div><div className="agreement-brand">RAHUL DEVELOPMENT STUDIO</div><h2>PROJECT DEVELOPMENT AGREEMENT</h2></div><div className="agreement-badge">{agreement.status.toUpperCase()} · v{agreement.version}</div></div><div className="agreement-meta"><Meta label="Agreement ID" value={agreement.agreement_code}/><Meta label="Deal ID" value={deal.deal_code}/><Meta label="Client" value={deal.client_name}/><Meta label="Project" value={deal.project_name}/></div><Section title="1. Parties"><p>This Project Development Agreement is entered into between <strong>Rahul Development Studio</strong> and <strong>{deal.client_name}</strong>{deal.organization?` (${deal.organization})`:""} for <strong>{deal.project_name}</strong>.</p></Section><Section title="2. Project Scope"><p>{deal.project_description||"The project will be developed according to the agreed scope and deliverables."}</p><p>Project type: <strong>{deal.project_type}</strong>. Technology: <strong>{deal.technology||"As mutually agreed"}</strong>.</p></Section><Section title="3. Commercial Terms"><Info items={[["Total project amount",money(deal.total_amount)],["Advance",money(deal.advance_amount)],["Remaining",money(deal.remaining_amount)],["Payment schedule",deal.payment_schedule||"As mutually agreed"]]}/></Section><Section title="4. Timeline & Support"><Info items={[["Start date",deal.start_date||"To be agreed"],["Expected delivery",deal.expected_delivery_date||"To be agreed"],["Revision rounds",String(deal.revision_rounds)],["Bug-fix support",`${deal.support_days} days`]]}/></Section><Section title="5. Scope & Deliverables"><div className="two-list"><div><strong>Scope</strong>{scope.length?scope.map(x=><p key={x.title}>• {x.title}</p>):<p>As agreed in project brief.</p>}</div><div><strong>Deliverables</strong>{deliverables.length?deliverables.map(x=><p key={x.title}>• {x.title}</p>):<p>As agreed in project brief.</p>}</div></div></Section><Section title="6. Agreement Notes"><p>{version?.snapshot?.notes||"No additional notes."}</p></Section><div className="declaration"><strong>Client Declaration</strong><p>I have reviewed the agreement and understand that any correction must be requested before signing. Once signed, this version becomes immutable.</p></div><div className="signature-placeholder"><div>CLIENT SIGNATURE<span>{agreement.status==="client_signed"||agreement.status==="executed"?"Signed":"Pending client signature"}</span></div><div>DEVELOPER COUNTERSIGN<span>{agreement.status==="executed"?"Executed":"Pending developer countersign"}</span></div></div></section>
 <aside className="agreement-actions panel"><div className="panel-title"><ShieldCheck size={16}/> Review & actions</div><p className="page-copy">Immutable signing, audit trail and final document storage are enabled.</p>{canClientSign&&<button className="btn primary" onClick={()=>setSigning(true)}><PenLine size={15}/> Sign Agreement</button>}{canCountersign&&<button className="btn primary" onClick={()=>setSigning(true)}><PenLine size={15}/> Countersign & Activate Project</button>}{agreement.status==="executed"&&<><div className="success-banner compact"><Check size={15}/> Agreement executed · Project active</div>{isDeveloper&&<button className="btn" disabled={provisioning} onClick={provisionPortal}><KeyRound size={15}/>{provisioning?"Provisioning…":"Generate client portal credentials"}</button>}{document?<button className="btn" disabled={pdfBusy} onClick={openSignedPdf}><Download size={15}/> Open final signed PDF</button>:isDeveloper?<button className="btn" disabled={pdfBusy} onClick={generateSignedPdf}><Download size={15}/>{pdfBusy?"Generating…":"Generate final signed PDF"}</button>:null}</>}{isClient&&canClientSign&&<button className="btn" onClick={()=>setCorrection(true)}><MessageSquare size={15}/> Request correction</button>}<div className="action-divider"/><div className="action-note"><strong>Version {agreement.version}</strong><br/>Created {new Date(agreement.created_at).toLocaleString("en-IN")}.<br/><br/>{document&&<>Final PDF SHA-256: <code>{document.content_hash?.slice(0,16)}…</code><br/>Stored privately in Supabase Storage.</>}</div></aside></div>
 {signing&&<div className="modal-backdrop"><div className="modal panel"><div className="panel-title"><PenLine size={16}/> {canCountersign?"Developer countersign":"Confirm & sign agreement"}</div><p className="page-copy">Your signature will be recorded with this agreement version and timestamped.</p><label>Full name<input value={signerName} onChange={e=>setSignerName(e.target.value)} placeholder="Full legal name" required/></label><label>Signature<textarea value={signature} onChange={e=>setSignature(e.target.value)} rows={3} placeholder="Type your full name as your electronic signature" required/></label>{canClientSign&&<label className="check-row"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/> I have reviewed the agreement and agree to its terms.</label>}<div className="modal-actions"><button className="btn" onClick={()=>setSigning(false)}>Cancel</button><button className="btn primary" disabled={submitting||!signerName.trim()||!signature.trim()||(canClientSign&&!accepted)} onClick={canCountersign?countersign:signAgreement}>{submitting?"Signing…":canCountersign?"Countersign & Activate":"Confirm & Sign Agreement"}</button></div></div></div>}
 {correction&&<div className="modal-backdrop"><form className="modal panel" onSubmit={submitCorrection}><div className="panel-title">Request a correction</div><p className="page-copy">Tell the developer exactly what needs to change. You cannot edit agreement data directly.</p><label>Section<select value={section} onChange={e=>setSection(e.target.value)}><option>General</option><option>Project Scope</option><option>Commercial Terms</option><option>Timeline & Support</option><option>Scope & Deliverables</option><option>Other</option></select></label><label>What needs correction?<textarea value={request} onChange={e=>setRequest(e.target.value)} rows={5} placeholder="Example: The project amount should be ₹18,000." required/></label><div className="modal-actions"><button type="button" className="btn" onClick={()=>setCorrection(false)}>Cancel</button><button className="btn primary" disabled={submitting}><Send size={15}/>{submitting?"Submitting…":"Submit request"}</button></div></form></div>}
 {credentials&&<div className="modal-backdrop"><div className="modal panel"><div className="panel-title"><KeyRound size={16}/> Client portal credentials</div><p className="page-copy">Give these credentials to the client securely. The temporary password is intentionally shown only here.</p><div className="credential-box"><div><span>Client ID</span><strong>{credentials.clientId}</strong><button className="icon-btn" onClick={()=>copy(credentials.clientId)} aria-label="Copy client ID"><Copy size={14}/></button></div><div><span>Email</span><strong>{credentials.email}</strong><button className="icon-btn" onClick={()=>copy(credentials.email)} aria-label="Copy email"><Copy size={14}/></button></div><div><span>Temporary password</span><strong>{credentials.temporaryPassword}</strong><button className="icon-btn" onClick={()=>copy(credentials.temporaryPassword)} aria-label="Copy temporary password"><Copy size={14}/></button></div></div><div className="action-note"><strong>First login:</strong> the client must change this temporary password before entering the project portal.</div><div className="modal-actions"><button className="btn primary" onClick={()=>setCredentials(null)}>Done</button></div></div></div>}</main></div>;
}
function money(value:number){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(Number(value||0));}
function Meta({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function Section({title,children}:{title:string;children:ReactNode}){return <section className="agreement-section"><h3>{title}</h3>{children}</section>}
function Info({items}:{items:string[][]}){return <div className="info-grid">{items.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>}
