"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { Check, Eraser, MessageSquare, Send, ShieldCheck, PenLine } from "lucide-react";
import { createClient } from "../../../lib/supabase/browser";

type Data={agreement:{id:string;agreement_code:string;status:string;version:number;sent_at:string|null;client_signed_at:string|null;developer_signed_at:string|null};deal:{client_id:string|null;client_name:string;organization:string;project_name:string;project_type:string;project_description:string|null;technology:string|null;start_date:string|null;expected_delivery_date:string|null;total_amount:number;advance_amount:number;remaining_amount:number;payment_schedule:string|null;revision_rounds:number;support_days:number};version_snapshot:{notes?:string}|null;scope:{title:string}[];deliverables:{title:string}[]};
async function hashToken(token:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}

export default function PublicAgreementPage({params}:{params:{token:string}}){
 const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[correction,setCorrection]=useState(false),[signing,setSigning]=useState(false),[section,setSection]=useState("General"),[request,setRequest]=useState(""),[submitting,setSubmitting]=useState(false),[message,setMessage]=useState(""),[signerName,setSignerName]=useState(""),[agreed,setAgreed]=useState(false),[signature,setSignature]=useState("");
 const canvasRef=useRef<HTMLCanvasElement>(null), drawing=useRef(false);
 useEffect(()=>{(async()=>{try{const s=createClient();const tokenHash=await hashToken(params.token);const {data:d,error:e}=await s.rpc("get_public_agreement",{p_token_hash:tokenHash});if(e)throw e;setData(d as Data)}catch(e){setError(e instanceof Error?e.message:"This agreement link is invalid or unavailable.")}finally{setLoading(false)}})()},[params.token]);
 useEffect(()=>{const c=canvasRef.current;if(!c)return;const ctx=c.getContext("2d");if(!ctx)return;ctx.lineWidth=2;ctx.lineCap="round";ctx.strokeStyle="#111827"},[signing]);
 function point(e:React.PointerEvent<HTMLCanvasElement>){const c=canvasRef.current!;const r=c.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
 function start(e:React.PointerEvent<HTMLCanvasElement>){drawing.current=true;e.currentTarget.setPointerCapture(e.pointerId);const p=point(e);const ctx=canvasRef.current!.getContext("2d")!;ctx.beginPath();ctx.moveTo(p.x,p.y)}
 function move(e:React.PointerEvent<HTMLCanvasElement>){if(!drawing.current)return;const p=point(e);const ctx=canvasRef.current!.getContext("2d")!;ctx.lineTo(p.x,p.y);ctx.stroke()}
 function end(){drawing.current=false;setSignature(canvasRef.current?.toDataURL("image/png")||"")}
 function clearSignature(){const c=canvasRef.current;if(c)c.getContext("2d")?.clearRect(0,0,c.width,c.height);setSignature("")}
 async function submitCorrection(e:FormEvent){e.preventDefault();if(!data||!request.trim())return;setSubmitting(true);setError("");try{const s=createClient();const tokenHash=await hashToken(params.token);const {error:e1}=await s.rpc("submit_public_correction_request",{p_token_hash:tokenHash,p_section:section,p_request_text:request.trim()});if(e1)throw e1;setMessage("Your correction request has been sent to Rahul Development Studio.");setRequest("");setCorrection(false)}catch(e){setError(e instanceof Error?e.message:"Unable to submit correction request.")}finally{setSubmitting(false)}}
 async function submitSignature(e:FormEvent){e.preventDefault();if(!data||!agreed||!signerName.trim()||!signature)return;setSubmitting(true);setError("");try{const s=createClient();const tokenHash=await hashToken(params.token);const {data:r,error:e1}=await s.rpc("sign_public_agreement",{p_token_hash:tokenHash,p_signer_name:signerName.trim(),p_signature_data:signature});if(e1)throw e1;setMessage(`Agreement ${r?.agreement_code||data.agreement.agreement_code} signed successfully. The developer can now countersign it.`);setSigning(false);setData({...data,agreement:{...data.agreement,status:"client_signed",client_signed_at:new Date().toISOString()}})}catch(e){setError(e instanceof Error?e.message:"Unable to sign this agreement.")}finally{setSubmitting(false)}}
 if(loading)return <main className="auth-shell"><div className="panel">Loading your agreement…</div></main>;
 if(error&&!data)return <main className="auth-shell"><div className="panel"><div className="eyebrow">Private agreement</div><h1>Link unavailable</h1><p className="page-copy">{error}</p></div></main>;
 if(!data)return null;const {agreement:a,deal,scope,deliverables}=data;const locked=["client_signed","executed","superseded"].includes(a.status);const canSign=["sent","under_review"].includes(a.status);
 return <main className="public-agreement"><div className="public-top"><div><div className="agreement-brand">RAHUL DEVELOPMENT STUDIO</div><div className="eyebrow">Private client agreement</div></div><span className={`status status-${a.status}`}>{a.status.replaceAll("_"," ")}</span></div>
 {message&&<div className="success-banner"><Check size={15}/>{message}</div>}{error&&<div className="form-error">{error}</div>}
 <section className="agreement-paper"><div className="agreement-header"><div><div className="agreement-brand">RAHUL DEVELOPMENT STUDIO</div><h1>PROJECT DEVELOPMENT AGREEMENT</h1></div><div className="agreement-badge">v{a.version}</div></div><div className="agreement-meta"><Meta label="Agreement ID" value={a.agreement_code}/><Meta label="Client" value={deal.client_name}/><Meta label="Project" value={deal.project_name}/><Meta label="Organization" value={deal.organization||"—"}/></div>
 <Section title="1. Parties"><p>This agreement is between <strong>Rahul Development Studio</strong> and <strong>{deal.client_name}</strong>{deal.organization?` (${deal.organization})`:""} for <strong>{deal.project_name}</strong>.</p></Section><Section title="2. Project Scope"><p>{deal.project_description||"The project will be developed according to the agreed scope and deliverables."}</p><p>Project type: <strong>{deal.project_type}</strong> · Technology: <strong>{deal.technology||"As mutually agreed"}</strong>.</p></Section><Section title="3. Commercial Terms"><Info items={[["Total project amount",money(deal.total_amount)],["Advance",money(deal.advance_amount)],["Remaining",money(deal.remaining_amount)],["Payment schedule",deal.payment_schedule||"As mutually agreed"]]}/></Section><Section title="4. Timeline & Support"><Info items={[["Start date",deal.start_date||"To be agreed"],["Expected delivery",deal.expected_delivery_date||"To be agreed"],["Revision rounds",String(deal.revision_rounds)],["Bug-fix support",`${deal.support_days} days`]]}/></Section><Section title="5. Scope & Deliverables"><div className="two-list"><div><strong>Scope</strong>{scope.length?scope.map(x=><p key={x.title}>• {x.title}</p>):<p>As agreed in project brief.</p>}</div><div><strong>Deliverables</strong>{deliverables.length?deliverables.map(x=><p key={x.title}>• {x.title}</p>):<p>As agreed in project brief.</p>}</div></div></Section><Section title="6. Agreement Notes"><p>{data.version_snapshot?.notes||"No additional notes."}</p></Section><div className="declaration"><strong>Before you sign</strong><p>Review all project, commercial and delivery terms carefully. If something is incorrect, request a correction before signing. Signed versions are immutable.</p></div></section>
 <section className="public-actions panel"><div><div className="panel-title"><ShieldCheck size={16}/> Client review</div><p className="page-copy">This private link is read-only. You cannot change agreement data directly.</p></div><div className="action-row">{!locked&&<button className="btn" onClick={()=>setCorrection(true)}><MessageSquare size={15}/> Request correction</button>}{canSign&&<button className="btn primary" onClick={()=>setSigning(true)}><PenLine size={15}/> Sign agreement</button>}{locked&&<div className="action-note"><strong>Signed version</strong><br/>This agreement version is locked and cannot be edited.</div>}</div></section>
 {correction&&<div className="modal-backdrop"><form className="modal panel" onSubmit={submitCorrection}><div className="panel-title"><MessageSquare size={16}/> Request a correction</div><p className="page-copy">Tell the developer what needs to change. Your request will not alter the agreement until the developer reviews it.</p><label>Section<select value={section} onChange={e=>setSection(e.target.value)}><option>General</option><option>Project Scope</option><option>Commercial Terms</option><option>Timeline & Support</option><option>Scope & Deliverables</option><option>Other</option></select></label><label>What needs correction?<textarea value={request} onChange={e=>setRequest(e.target.value)} rows={5} placeholder="Example: The project amount should be ₹18,000." required/></label><div className="modal-actions"><button type="button" className="btn" onClick={()=>setCorrection(false)}>Cancel</button><button className="btn primary" disabled={submitting}><Send size={15}/>{submitting?"Sending…":"Submit correction"}</button></div></form></div>}
 {signing&&<div className="modal-backdrop"><form className="modal panel signature-modal" onSubmit={submitSignature}><div className="panel-title"><PenLine size={16}/> Sign agreement</div><p className="page-copy">By signing, you confirm that you have reviewed this agreement and agree to its terms.</p><label>Full name<input value={signerName} onChange={e=>setSignerName(e.target.value)} placeholder="Your full legal name" required/></label><label>Signature<div className="signature-wrap"><canvas ref={canvasRef} width={640} height={180} onPointerDown={start} onPointerMove={move} onPointerUp={end} onPointerCancel={end} /></div><button type="button" className="btn" onClick={clearSignature}><Eraser size={14}/> Clear signature</button></label><label className="check-row"><input type="checkbox" checked={agreed} onChange={e=>setAgreed(e.target.checked)}/><span>I have reviewed the agreement and agree to its terms.</span></label><div className="modal-actions"><button type="button" className="btn" onClick={()=>setSigning(false)}>Cancel</button><button className="btn primary" disabled={submitting||!agreed||!signerName.trim()||!signature}><Check size={15}/>{submitting?"Signing…":"Confirm & Sign Agreement"}</button></div></form></div>}
 </main>
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="agreement-section"><h2>{title}</h2>{children}</section>}function Meta({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}function Info({items}:{items:string[][]}){return <div className="agreement-info-grid">{items.map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div>}function money(v:number){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v||0)}
