"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { Check, Eraser, MessageSquare, PenLine, Send, ShieldCheck } from "lucide-react";
import { createClient } from "../../../lib/supabase/browser";
import styles from "./page.module.css";

type Data={agreement:{id:string;agreement_code:string;status:string;version:number;sent_at:string|null;client_signed_at:string|null;developer_signed_at:string|null};deal:{client_name:string;organization:string;project_name:string;project_type:string;project_description:string|null;technology:string|null;start_date:string|null;expected_delivery_date:string|null;total_amount:number;advance_amount:number;remaining_amount:number;payment_schedule:string|null;revision_rounds:number;support_days:number};version_snapshot:{notes?:string}|null;scope:{title:string}[];deliverables:{title:string}[]};
async function hashToken(token:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
const money=(v:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v||0);

export default function PublicAgreementPage({params}:{params:Promise<{token:string}>}){
 const [data,setData]=useState<Data|null>(null),[token,setToken]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState(""),[correction,setCorrection]=useState(false),[signing,setSigning]=useState(false),[section,setSection]=useState("General"),[request,setRequest]=useState(""),[signerName,setSignerName]=useState(""),[agreed,setAgreed]=useState(false),[signature,setSignature]=useState(""),[submitting,setSubmitting]=useState(false);
 const canvasRef=useRef<HTMLCanvasElement>(null),drawing=useRef(false);
 useEffect(()=>{let active=true;(async()=>{try{const p=await params;if(active)setToken(p.token)}catch{if(active){setError("This agreement link is invalid.");setLoading(false)}}})();return()=>{active=false}},[params]);
 useEffect(()=>{if(!token)return;(async()=>{try{const s=createClient();const h=await hashToken(token);const {data:d,error:e}=await s.rpc("get_public_agreement",{p_token_hash:h});if(e)throw e;if(!d)throw new Error("Agreement not found.");setData(d as Data)}catch(e){setError(e instanceof Error?e.message:"This agreement link is unavailable.")}finally{setLoading(false)}})()},[token]);
 useEffect(()=>{if(!signing)return;const c=canvasRef.current,ctx=c?.getContext("2d");if(ctx){ctx.lineWidth=2.2;ctx.lineCap="round";ctx.strokeStyle="#17191d"}},[signing]);
 const point=(e:React.PointerEvent<HTMLCanvasElement>)=>{const c=canvasRef.current!,r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*(c.width/r.width),y:(e.clientY-r.top)*(c.height/r.height)}};
 const start=(e:React.PointerEvent<HTMLCanvasElement>)=>{drawing.current=true;e.currentTarget.setPointerCapture(e.pointerId);const p=point(e),ctx=canvasRef.current!.getContext("2d")!;ctx.beginPath();ctx.moveTo(p.x,p.y)};
 const move=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!drawing.current)return;const p=point(e),ctx=canvasRef.current!.getContext("2d")!;ctx.lineTo(p.x,p.y);ctx.stroke()};
 const end=()=>{drawing.current=false;setSignature(canvasRef.current?.toDataURL("image/png")||"")};
 const clearSignature=()=>{const c=canvasRef.current;if(c)c.getContext("2d")?.clearRect(0,0,c.width,c.height);setSignature("")};
 async function submitCorrection(e:FormEvent){e.preventDefault();if(!token||!request.trim())return;setSubmitting(true);setError("");try{const s=createClient(),h=await hashToken(token);const {error:e1}=await s.rpc("submit_public_correction_request",{p_token_hash:h,p_section:section,p_request_text:request.trim()});if(e1)throw e1;setMessage("Your correction request has been sent. Rahul Development Studio will review it before any signing takes place.");setRequest("");setCorrection(false);if(data)setData({...data,agreement:{...data.agreement,status:"correction_requested"}})}catch(e){setError(e instanceof Error?e.message:"Unable to submit correction request.")}finally{setSubmitting(false)}}
 async function submitSignature(e:FormEvent){e.preventDefault();if(!token||!agreed||!signerName.trim()||!signature)return;setSubmitting(true);setError("");try{const s=createClient(),h=await hashToken(token);const {data:r,error:e1}=await s.rpc("sign_public_agreement",{p_token_hash:h,p_signer_name:signerName.trim(),p_signature_data:signature});if(e1)throw e1;setMessage(`Agreement ${r?.agreement_code||data?.agreement.agreement_code||""} signed successfully. Rahul Development Studio will countersign it next.`);setSigning(false);if(data)setData({...data,agreement:{...data.agreement,status:"client_signed",client_signed_at:new Date().toISOString()}})}catch(e){setError(e instanceof Error?e.message:"Unable to sign this agreement.")}finally{setSubmitting(false)}}
 if(loading)return <main className={styles.loading}>Loading your private agreement…</main>;
 if(!data)return <main className={styles.page}><div className={styles.wrap}><div className={styles.error}><strong>Agreement unavailable.</strong><br/>{error||"This private link may be invalid or no longer available."}</div></div></main>;
 const {agreement:a,deal,scope,deliverables}=data;const canSign=["sent","under_review"].includes(a.status),locked=["client_signed","executed","superseded"].includes(a.status);
 return <main className={styles.page}><div className={styles.wrap}>
  <header className={styles.top}><div><div className={styles.brand}>Rahul Development Studio</div><div className={styles.sub}>Private project agreement · Secure client review</div></div><span className={styles.status}>{a.status.replaceAll("_"," ")}</span></header>
  {message&&<div className={styles.success}><Check size={15}/> {message}</div>}{error&&<div className={styles.error}>{error}</div>}
  <section className={styles.hero}><div><h1>{deal.project_name}</h1><p>This agreement is prepared for {deal.client_name}{deal.organization?` · ${deal.organization}`:""}. Review the terms carefully before requesting a correction or signing.</p></div><div className={styles.heroMeta}><div><span>Agreement</span><strong>{a.agreement_code}</strong></div><div><span>Version</span><strong>Version {a.version}</strong></div><div><span>Project type</span><strong>{deal.project_type}</strong></div></div></section>
  <div className={styles.layout}><article className={styles.paper}>
   <AgreementSection title="Parties"><p>This Project Development Agreement is entered into between <strong>Rahul Development Studio</strong> and <strong>{deal.client_name}</strong>{deal.organization?` (${deal.organization})`:""} for the project <strong>{deal.project_name}</strong>.</p></AgreementSection>
   <AgreementSection title="Project scope"><p>{deal.project_description||"The project will be developed according to the agreed scope and deliverables."}</p><p>Technology: <strong>{deal.technology||"As mutually agreed"}</strong></p></AgreementSection>
   <AgreementSection title="Commercial terms"><div className={styles.grid}><Stat label="Total project amount" value={money(deal.total_amount)}/><Stat label="Advance" value={money(deal.advance_amount)}/><Stat label="Remaining" value={money(deal.remaining_amount)}/><Stat label="Payment schedule" value={deal.payment_schedule||"As mutually agreed"}/></div></AgreementSection>
   <AgreementSection title="Timeline & support"><div className={styles.grid}><Stat label="Start date" value={deal.start_date||"To be agreed"}/><Stat label="Expected delivery" value={deal.expected_delivery_date||"To be agreed"}/><Stat label="Revision rounds" value={String(deal.revision_rounds)}/><Stat label="Bug-fix support" value={`${deal.support_days} days`}/></div></AgreementSection>
   <AgreementSection title="Scope & deliverables"><div className={styles.lists}><div><strong>Included scope</strong>{scope.length?scope.map(x=><p key={x.title}>• {x.title}</p>):<p>As agreed in the project brief.</p>}</div><div><strong>Deliverables</strong>{deliverables.length?deliverables.map(x=><p key={x.title}>• {x.title}</p>):<p>As agreed in the project brief.</p>}</div></div></AgreementSection>
   <AgreementSection title="Additional notes"><p>{data.version_snapshot?.notes||"No additional notes."}</p></AgreementSection>
  </article>
  <aside className={styles.side}><ShieldCheck size={22}/><h2>Review & sign</h2><p>You do not need a client account to review or sign this agreement. Portal credentials are created only after both parties have completed signing.</p>{canSign&&<><button className={styles.primary} onClick={()=>setSigning(true)}><PenLine size={16}/> Review & sign agreement</button><button className={styles.secondary} onClick={()=>setCorrection(true)}><MessageSquare size={16}/> Request a correction</button></>}{locked&&<div className={styles.locked}><strong>{a.status==="client_signed"?"Client signature recorded":"Agreement completed"}</strong><br/>{a.status==="client_signed"?"The agreement is waiting for the developer's countersignature.":"This version is locked and cannot be changed."}</div>}<div className={styles.steps}><Step n="1" title="Review" text="Read the scope, commercial terms and delivery commitments."/><Step n="2" title="Request correction" text="Ask for changes before signing if anything is incorrect."/><Step n="3" title="Sign" text="Confirm acceptance and add your electronic signature."/><Step n="4" title="Get portal access" text="Credentials are issued after both parties complete signing."/></div><div className={styles.notice}>For security, this private link is the only access needed for agreement review. Do not share it publicly.</div></aside>
  </div>
 </div>
 {correction&&<div className={styles.modalBg}><form className={styles.modal} onSubmit={submitCorrection}><h2>Request a correction</h2><p>Describe exactly what needs to change. The agreement remains unsigned until the developer reviews the request.</p><label className={styles.field}>Agreement section<select value={section} onChange={e=>setSection(e.target.value)}><option>General</option><option>Project scope</option><option>Commercial terms</option><option>Timeline & support</option><option>Scope & deliverables</option><option>Other</option></select></label><label className={styles.field}>What should be corrected?<textarea rows={6} value={request} onChange={e=>setRequest(e.target.value)} placeholder="Describe the correction clearly…" required/></label><div className={styles.actions}><button type="button" className={styles.cancel} onClick={()=>setCorrection(false)}>Cancel</button><button className={styles.primary} style={{width:"auto"}} disabled={submitting}><Send size={15}/>{submitting?"Sending…":"Send request"}</button></div></form></div>}
 {signing&&<div className={styles.modalBg}><form className={styles.modal} onSubmit={submitSignature}><h2>Sign this agreement</h2><p>By signing, you confirm that you reviewed this version and agree to its terms. The developer will countersign before the project is activated.</p><label className={styles.field}>Your full name<input value={signerName} onChange={e=>setSignerName(e.target.value)} placeholder={deal.client_name} required/></label><label className={styles.field}>Draw your signature<div className={styles.signature}><canvas className={styles.canvas} ref={canvasRef} width={900} height={300} onPointerDown={start} onPointerMove={move} onPointerUp={end} onPointerCancel={end}/></div><button type="button" className={styles.clear} onClick={clearSignature}><Eraser size={13}/> Clear signature</button></label><label className={styles.check}><input type="checkbox" checked={agreed} onChange={e=>setAgreed(e.target.checked)}/><span>I confirm that I have reviewed this agreement and agree to the terms shown in this version.</span></label><div className={styles.actions}><button type="button" className={styles.cancel} onClick={()=>setSigning(false)}>Cancel</button><button className={styles.primary} style={{width:"auto"}} disabled={submitting||!agreed||!signerName.trim()||!signature}><Check size={15}/>{submitting?"Signing…":"Confirm & sign"}</button></div></form></div>}
 </main>
}
function AgreementSection({title,children}:{title:string;children:React.ReactNode}){return <section className={styles.section}><h2>{title}</h2>{children}</section>}
function Stat({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function Step({n,title,text}:{n:string;title:string;text:string}){return <div className={styles.step}><div className={styles.num}>{n}</div><div><strong>{title}</strong><span>{text}</span></div></div>}
