"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Check, ExternalLink, FileText, MessageSquare, X } from "lucide-react";
import { createClient } from "../../lib/supabase/browser";

type Correction={id:string;agreement_id:string;client_id:string;section:string;request_text:string;status:string;developer_response:string|null;reviewed_at:string|null;created_at:string};
type Agreement={id:string;agreement_code:string;deal_id:string;status:string;version:number};
type Deal={id:string;project_name:string;client_name:string;organization:string};
const statusLabel:Record<string,string>={pending:"Pending",accepted:"Accepted",rejected:"Rejected"};

export default function CorrectionsPage(){
 const [items,setItems]=useState<Correction[]>([]),[agreements,setAgreements]=useState<Agreement[]>([]),[deals,setDeals]=useState<Deal[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[selected,setSelected]=useState<Correction|null>(null),[response,setResponse]=useState(""),[busy,setBusy]=useState(false),[filter,setFilter]=useState("pending");
 const load=async()=>{const s=createClient();const [{data:c,error:ce},{data:a,error:ae}]=await Promise.all([s.from("correction_requests").select("*").order("created_at",{ascending:false}),s.from("agreements").select("id,agreement_code,deal_id,status,version").order("created_at",{ascending:false})]);if(ce||ae){setError(ce?.message||ae?.message||"Unable to load correction requests.");setLoading(false);return}const dealsByIds=(a||[]).map(x=>x.deal_id);const {data:d}=dealsByIds.length?await s.from("deals").select("id,project_name,client_name,organization").in("id",dealsByIds):{data:[]};setItems(c||[]);setAgreements(a||[]);setDeals(d||[]);setLoading(false)};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>filter==="all"?items:items.filter(x=>x.status===filter),[items,filter]);
 const meta=(id:string)=>{const a=agreements.find(x=>x.id===id);const d=deals.find(x=>x.id===a?.deal_id);return {a,d}};
 async function review(e:FormEvent,decision:"accepted"|"rejected"){e.preventDefault();if(!selected)return;setBusy(true);setError("");try{const s=createClient();const {data,error:e1}=await s.rpc("review_correction_request",{p_request_id:selected.id,p_decision:decision,p_response:response.trim()||null});if(e1)throw e1;setItems(prev=>prev.map(x=>x.id===selected.id?{...x,status:decision,developer_response:response.trim()||null,reviewed_at:new Date().toISOString()}:x));setSelected(null);setResponse("");if(decision==="accepted")window.location.href=`/agreements/${selected.agreement_id}`;else await load()}catch(err){setError(err instanceof Error?err.message:"Unable to review request.")}finally{setBusy(false)}}
 if(loading)return <main className="main"><div className="panel">Loading correction requests…</div></main>;
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">R</div><div><div className="brand-title">Rahul Development Studio</div><div className="brand-subtitle">Client Management</div></div></div><nav className="nav"><a className="nav-item" href="/">Dashboard</a><a className="nav-item" href="/agreements"><FileText size={16}/> Agreements</a><a className="nav-item" href="/projects">Projects</a><a className="nav-item" href="/clients">Clients</a><a className="nav-item active" href="/corrections"><MessageSquare size={16}/> Corrections</a><a className="nav-item" href="/completed">Completed</a><a className="nav-item" href="/settings">Settings</a></nav></aside><main className="main"><header className="topbar"><div><div className="eyebrow">Client feedback</div><h1>Correction requests</h1><p className="page-copy">Review client requests before an agreement is signed.</p></div><select className="btn" value={filter} onChange={e=>setFilter(e.target.value)}><option value="pending">Pending</option><option value="accepted">Accepted</option><option value="rejected">Rejected</option><option value="all">All requests</option></select></header>{error&&<div className="form-error">{error}</div>}<section className="panel"><div className="panel-header"><div className="panel-title"><MessageSquare size={16}/> Requests</div><span className="eyebrow">{filtered.length} shown</span></div>{filtered.length?filtered.map(r=>{const {a,d}=meta(r.agreement_id);return <article className="project" key={r.id}><div><div className="project-name">{d?.project_name||"Project"}</div><div className="project-client">{a?.agreement_code||"Agreement"} · {d?.client_name||"Client"} · {r.section}</div><p className="page-copy request-copy">{r.request_text}</p>{r.developer_response&&<p className="request-response"><strong>Developer:</strong> {r.developer_response}</p>}</div><span className={`status status-${r.status}`}>{statusLabel[r.status]||r.status}</span><div className="project-status">{r.status==="pending"?<button className="btn" onClick={()=>setSelected(r)}>Review</button>:<a className="btn" href={`/agreements/${r.agreement_id}`}>Open agreement <ExternalLink size={13}/></a>}</div></article>}) : <div className="empty-state">No {filter==="all"?"":filter+" "}correction requests.</div>}</section></main>
 {selected&&<div className="modal-backdrop"><form className="modal panel" onSubmit={e=>review(e,"accepted")}><div className="panel-title"><MessageSquare size={16}/> Review correction</div><div className="review-box"><span>{meta(selected.agreement_id).a?.agreement_code} · {selected.section}</span><strong>{selected.request_text}</strong></div><label>Developer response<textarea value={response} onChange={e=>setResponse(e.target.value)} rows={4} placeholder="Optional message to the client…"/></label><p className="page-copy">Accepting returns the agreement to <strong>Under review</strong>. Update the agreement data, create the next version, and send the revised version back to the client.</p><div className="modal-actions"><button type="button" className="btn" onClick={()=>{setSelected(null);setResponse("")}}>Cancel</button><button type="button" className="btn danger" disabled={busy} onClick={e=>review(e as unknown as FormEvent,"rejected")}><X size={14}/> Reject</button><button className="btn primary" disabled={busy}><Check size={14}/>{busy?"Saving…":"Accept & update"}</button></div></form></div>}
 </div>;
}
