"use client";

import { useEffect, useState } from "react";
import { ArrowUpRight, FileSignature, Plus } from "lucide-react";
import { createClient } from "../../lib/supabase/browser";

type Agreement = { id:string; agreement_code:string; status:string; current_version:number; sent_at:string|null; client_signed_at:string|null; developer_signed_at:string|null; project_id:string; client_id:string; projects?: { name:string } | null };

type Project = { id:string; name:string; client_id:string; status:string; expected_delivery_date:string|null };

const statusLabel: Record<string,string> = { draft:"Draft", sent:"Sent to client", under_review:"Under review", correction_requested:"Correction requested", client_signed:"Client signed", executed:"Executed", superseded:"Superseded" };

export default function AgreementsPage(){
 const [agreements,setAgreements]=useState<Agreement[]>([]),[projects,setProjects]=useState<Project[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[creating,setCreating]=useState(false);
 useEffect(()=>{let mounted=true;(async()=>{const supabase=createClient();const [{data:a,error:ae},{data:p,error:pe}]=await Promise.all([supabase.from("agreements").select("id,agreement_code,status,current_version,sent_at,client_signed_at,developer_signed_at,project_id,client_id,projects(name)").order("created_at",{ascending:false}),supabase.from("projects").select("id,name,client_id,status,expected_delivery_date").order("created_at",{ascending:false})]);if(!mounted)return;if(ae||pe)setError(ae?.message||pe?.message||"Unable to load agreements.");setAgreements((a||[]) as Agreement[]);setProjects(p||[]);setLoading(false)})();return()=>{mounted=false}},[]);
 async function createAgreement(project:Project){setCreating(true);setError("");const supabase=createClient();const code=`RDS-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;const {data,error}=await supabase.from("agreements").insert({agreement_code:code,project_id:project.id,client_id:project.client_id,status:"draft",current_version:1}).select("id").single();if(error||!data){setError(error?.message||"Unable to create agreement.");setCreating(false);return}const {error:versionError}=await supabase.from("agreement_versions").insert({agreement_id:data.id,version:1,payload:{project_name:project.name},created_by:(await supabase.auth.getUser()).data.user?.id});if(versionError){await supabase.from("agreements").delete().eq("id",data.id);setError(versionError.message);setCreating(false);return}window.location.href=`/agreements/${data.id}`;}
 if(loading)return <main className="main"><div className="panel">Loading agreements…</div></main>;
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">R</div><div><div className="brand-title">Rahul Development Studio</div><div className="brand-subtitle">Client Management</div></div></div><nav className="nav"><a className="nav-item" href="/">Dashboard</a><a className="nav-item active" href="/agreements"><FileSignature size={16}/> Agreements</a><a className="nav-item" href="/projects">Projects</a><a className="nav-item" href="/clients">Clients</a><a className="nav-item" href="/completed">Completed</a><a className="nav-item" href="/settings">Settings</a></nav></aside><main className="main"><header className="topbar"><div><div className="eyebrow">Agreement workspace</div><h1>Agreements</h1><p className="page-copy">Draft, review and send project agreements to clients.</p></div><div className="top-actions"><select className="btn" disabled={creating||!projects.length} defaultValue=""><option value="" disabled>Create from project…</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="btn primary" disabled={creating||!projects.length} onClick={(e)=>{const id=(e.currentTarget.previousElementSibling as HTMLSelectElement)?.value;const project=projects.find(p=>p.id===id);if(project)createAgreement(project)}}><Plus size={15}/> {creating?"Creating…":"New Agreement"}</button></div></header>{error&&<div className="form-error">{error}</div>}<section className="panel"><div className="panel-header"><div className="panel-title">Agreement register</div><span className="eyebrow">{agreements.length} total</span></div>{agreements.length?agreements.map(a=><a className="project" href={`/agreements/${a.id}`} key={a.id}><div><div className="project-name">{a.projects?.name||"Project Agreement"}</div><div className="project-client">{a.agreement_code} · Version {a.current_version}</div></div><span className="status">{statusLabel[a.status]||a.status}</span><div className="project-status">{a.status==="executed"?"Executed":a.status==="client_signed"?"Awaiting countersign":"Open editor"}<ArrowUpRight size={14}/></div></a>):<div className="empty-state">No agreements yet. Create one from an existing project.</div>}</section></main></div>;
}
