"use client";

import { useEffect, useState } from "react";
import { ArrowUpRight, FileSignature, Plus } from "lucide-react";
import { createClient } from "../../lib/supabase/browser";

type Agreement={id:string;agreement_code:string;deal_id:string;client_id:string|null;status:string;version:number;sent_at:string|null;client_signed_at:string|null;developer_signed_at:string|null;created_at:string};
type Deal={id:string;deal_code:string;project_name:string;client_name:string;organization:string;status:string};
const labels:Record<string,string>={draft:"Draft",sent:"Sent to client",under_review:"Under review",correction_requested:"Correction requested",client_signed:"Client signed",executed:"Executed",superseded:"Superseded"};

export default function AgreementsPage(){
 const [agreements,setAgreements]=useState<Agreement[]>([]),[deals,setDeals]=useState<Deal[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[creating,setCreating]=useState(false),[selectedDeal,setSelectedDeal]=useState("");
 useEffect(()=>{let mounted=true;(async()=>{const s=createClient();const [{data:a,error:ae},{data:d,error:de}]=await Promise.all([s.from("agreements").select("id,agreement_code,deal_id,client_id,status,version,sent_at,client_signed_at,developer_signed_at,created_at").order("created_at",{ascending:false}),s.from("deals").select("id,deal_code,project_name,client_name,organization,status").order("created_at",{ascending:false})]);if(!mounted)return;if(ae||de){setError(ae?.message||de?.message||"Unable to load agreements.");setLoading(false);return}setAgreements(a||[]);setDeals(d||[]);setLoading(false)})();return()=>{mounted=false}},[]);
 async function createAgreement(){const deal=deals.find(d=>d.id===selectedDeal);if(!deal)return;setCreating(true);setError("");const s=createClient();const {data:user}=await s.auth.getUser();if(!user.user){setError("Please sign in again.");setCreating(false);return}const {data:existing}=await s.from("agreements").select("id").eq("deal_id",deal.id).maybeSingle();if(existing){window.location.href=`/agreements/${existing.id}`;return}const {data:a,error}=await s.from("agreements").insert({deal_id:deal.id,client_id:null,status:"draft",version:1}).select("id").single();if(error||!a){setError(error?.message||"Unable to create agreement.");setCreating(false);return}const snapshot={deal:{...deal},notes:""};const {error:ve}=await s.from("agreement_versions").insert({agreement_id:a.id,version:1,snapshot,content_hash:null});if(ve){await s.from("agreements").delete().eq("id",a.id);setError(ve.message);setCreating(false);return}window.location.href=`/agreements/${a.id}`;}
 if(loading)return <main className="main"><div className="panel">Loading agreements…</div></main>;
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">R</div><div><div className="brand-title">Rahul Development Studio</div><div className="brand-subtitle">Client Management</div></div></div><nav className="nav"><a className="nav-item" href="/">Dashboard</a><a className="nav-item active" href="/agreements"><FileSignature size={16}/> Agreements</a><a className="nav-item" href="/projects">Projects</a><a className="nav-item" href="/clients">Clients</a><a className="nav-item" href="/completed">Completed</a><a className="nav-item" href="/settings">Settings</a></nav></aside><main className="main"><header className="topbar"><div><div className="eyebrow">Agreement workspace</div><h1>Agreements</h1><p className="page-copy">Draft, review and send project agreements to clients.</p></div><div className="top-actions"><select className="btn" value={selectedDeal} disabled={creating||!deals.length} onChange={e=>setSelectedDeal(e.target.value)}><option value="">Create from deal…</option>{deals.map(d=><option key={d.id} value={d.id}>{d.project_name} · {d.client_name}</option>)}</select><button className="btn primary" disabled={creating||!selectedDeal} onClick={createAgreement}><Plus size={15}/> {creating?"Creating…":"New Agreement"}</button></div></header>{error&&<div className="form-error">{error}</div>}<section className="panel"><div className="panel-header"><div className="panel-title">Agreement register</div><span className="eyebrow">{agreements.length} total</span></div>{agreements.length?agreements.map(a=>{const d=deals.find(x=>x.id===a.deal_id);return <a className="project" href={`/agreements/${a.id}`} key={a.id}><div><div className="project-name">{d?.project_name||"Project Agreement"}</div><div className="project-client">{a.agreement_code} · {d?.client_name||"Client"} · Version {a.version}</div></div><span className="status">{labels[a.status]||a.status}</span><div className="project-status">{a.status==="executed"?"Executed":a.status==="client_signed"?"Awaiting countersign":"Open agreement"}<ArrowUpRight size={14}/></div></a>}) : <div className="empty-state">No agreements yet. Create one from an existing deal.</div>}</section></main></div>;
}
