-- Keep the production RDS-Business database migration history aligned with the
-- live ownership hardening applied on 2026-08-21.
--
-- The live migration tightens these SECURITY DEFINER RPCs so authenticated
-- developers may only mutate resources belonging to their own deal:
--   developer_countersign_agreement
--   review_correction_request
--   update_project_topic_status
--   confirm_project_handover
--
-- Each function keeps SET search_path = public, checks auth.uid(), verifies
-- the developer role, and then verifies deals.developer_id = auth.uid() before
-- performing any mutation.

create or replace function public.developer_countersign_agreement(p_agreement_id uuid,p_signer_name text,p_signature_data text) returns jsonb language plpgsql security definer set search_path=public as $$ declare a public.agreements; d public.deals; uid uuid:=auth.uid(); project_id uuid; begin if uid is null or not public.is_developer() then raise exception 'Only a developer can countersign an agreement'; end if; if trim(coalesce(p_signer_name,''))='' or trim(coalesce(p_signature_data,''))='' then raise exception 'Signer name and signature are required'; end if; select * into a from public.agreements where id=p_agreement_id for update; if a.id is null then raise exception 'Agreement not found'; end if; select * into d from public.deals where id=a.deal_id for update; if d.id is null then raise exception 'Deal not found'; end if; if d.developer_id<>uid then raise exception 'You are not authorized to countersign this agreement'; end if; if a.status<>'client_signed' then raise exception 'Client must sign before countersigning'; end if; if exists(select 1 from public.signatures where agreement_id=a.id and signer_role='developer') then raise exception 'Developer countersignature already exists'; end if; insert into public.signatures(agreement_id,signer_id,signer_role,signer_name,signature_data) values(a.id,uid,'developer',trim(p_signer_name),p_signature_data); update public.agreements set status='executed',developer_signed_at=now(),executed_at=now(),updated_at=now() where id=a.id; update public.deals set status='active',client_id=a.client_id,updated_at=now() where id=a.deal_id; insert into public.projects(deal_id,agreement_id,client_id,project_name,status,start_date,expected_delivery_date) values(a.deal_id,a.id,a.client_id,d.project_name,'in_development',d.start_date,d.expected_delivery_date) on conflict(deal_id) do update set agreement_id=excluded.agreement_id,client_id=excluded.client_id,project_name=excluded.project_name,status='in_development',start_date=excluded.start_date,expected_delivery_date=excluded.expected_delivery_date,updated_at=now() returning id into project_id; return jsonb_build_object('success',true,'status','executed','project_id',project_id); end; $$;

create or replace function public.review_correction_request(p_request_id uuid,p_decision public.correction_status,p_response text default null) returns jsonb language plpgsql security definer set search_path=public as $$ declare r public.correction_requests; a public.agreements; d public.deals; uid uuid:=auth.uid(); begin if uid is null or not public.is_developer() then raise exception 'Only a developer can review correction requests'; end if; if p_decision not in ('accepted','rejected') then raise exception 'Decision must be accepted or rejected'; end if; select * into r from public.correction_requests where id=p_request_id for update; if r.id is null then raise exception 'Correction request not found'; end if; select * into a from public.agreements where id=r.agreement_id for update; if a.id is null then raise exception 'Agreement not found'; end if; select * into d from public.deals where id=a.deal_id; if d.id is null or d.developer_id<>uid then raise exception 'You are not authorized to review this correction request'; end if; if a.status in ('client_signed','executed','superseded') then raise exception 'Signed agreements are immutable; use an amendment instead'; end if; update public.correction_requests set status=p_decision,developer_response=nullif(trim(coalesce(p_response,'')),''),reviewed_at=now() where id=r.id returning * into r; if p_decision='accepted' then update public.agreements set status='under_review',updated_at=now() where id=a.id; elsif not exists(select 1 from public.correction_requests where agreement_id=a.id and status='pending') then update public.agreements set status='under_review',updated_at=now() where id=a.id; end if; return jsonb_build_object('success',true,'request_id',r.id,'decision',r.status,'agreement_id',a.id,'agreement_status',(select status from public.agreements where id=a.id)); end; $$;

create or replace function public.update_project_topic_status(p_topic_id uuid,p_status text) returns jsonb language plpgsql security definer set search_path=public as $$ declare uid uuid:=auth.uid(); t public.phase_topics; p public.projects; d public.deals; old text; total_count integer; completed_count integer; progress_percent integer; new_project_status text; begin if uid is null or not public.is_developer() then raise exception 'Only a developer can update project progress'; end if; if p_status not in ('pending','in_progress','completed') then raise exception 'Invalid topic status'; end if; select * into t from public.phase_topics where id=p_topic_id for update; if t.id is null then raise exception 'Topic not found'; end if; select * into p from public.projects where id=t.project_id for update; if p.id is null then raise exception 'Project not found'; end if; select * into d from public.deals where id=p.deal_id; if d.id is null or d.developer_id<>uid then raise exception 'You are not authorized to update this project'; end if; old:=t.status::text; update public.phase_topics set status=p_status::public.topic_status,completed_at=case when p_status='completed' then now() else null end,updated_at=now() where id=t.id; select count(*),count(*) filter(where status='completed') into total_count,completed_count from public.phase_topics where project_id=t.project_id; progress_percent:=case when total_count=0 then 0 else round((completed_count::numeric/total_count::numeric)*100)::integer end; if total_count>0 and completed_count=total_count then new_project_status:='development_complete'; update public.projects set status='development_complete',development_completed_at=coalesce(development_completed_at,now()),updated_at=now() where id=t.project_id and status<>'completed'; else new_project_status:='in_development'; update public.projects set status='in_development',development_completed_at=null,updated_at=now() where id=t.project_id and status<>'completed'; end if; insert into public.progress_history(project_id,phase_id,topic_id,changed_by,progress_percent,old_status,new_status,note) values(t.project_id,t.phase_id,t.id,uid,progress_percent,old,p_status,format('Topic status changed from %s to %s',old,p_status)); return jsonb_build_object('success',true,'project_status',new_project_status,'total_topics',total_count,'completed_topics',completed_count,'progress_percent',progress_percent); end; $$;

create or replace function public.confirm_project_handover(p_project_id uuid,p_handover_note text default null) returns jsonb language plpgsql security definer set search_path=public as $$ declare uid uuid:=auth.uid(); p public.projects; d public.deals; completed_at timestamptz:=now(); begin if uid is null or not public.is_developer() then raise exception 'Only a developer can confirm handover'; end if; select * into p from public.projects where id=p_project_id for update; if p.id is null then raise exception 'Project not found'; end if; select * into d from public.deals where id=p.deal_id; if d.id is null or d.developer_id<>uid then raise exception 'You are not authorized to confirm this project handover'; end if; if p.status<>'development_complete' then raise exception 'Development must be complete before handover'; end if; update public.projects set status='completed',handover_confirmed_at=completed_at,handover_confirmed_by=uid,handover_note=nullif(trim(p_handover_note),''),handover_at=completed_at,completed_at=completed_at,updated_at=completed_at where id=p.id; update public.deals set status='completed',updated_at=completed_at where id=p.deal_id; return jsonb_build_object('success',true,'status','completed','completed_at',completed_at,'handover_confirmed_by',uid,'handover_note',nullif(trim(p_handover_note),'') ); end; $$;
